name: PR Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nix
        uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Lint
        run: make lint

      - name: Check Formatting
        run: stylua --check lua/ tests/

      - name: Test
        run: make test
